### ISSUE TITLE
Error: No element found for selector: #icp-touch-link-cop

### ISSUE THREAD

**Issue by fab1o** [dimitryzub/ecommerce-scraper-js#3]
```js
const result = await amazon.getListingInfo(
        'https://www.amazon.com/dp/B0812JPZFT',
        'USD',
        'English',
        0
    );

    return result;
```

causes error:

```
Error: No element found for selector: #icp-touch-link-cop
    at assert (/Users/fabio/Dev/amazon/node_modules/puppeteer-core/lib/cjs/puppeteer/util/assert.js:28:15)
    at IsolatedWorld.click (/Users/fabio/Dev/amazon/node_modules/puppeteer-core/lib/cjs/puppeteer/common/IsolatedWorld.js:184:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getAmazonListingInfo (file:///Users/fabio/Dev/amazon/node_modules/ecommerce-scraper-js/amazon/getAmazonListingInfo.js:124:5)
    at async Object.getListingInfo (file:///Users/fabio/Dev/amazon/node_modules/ecommerce-scraper-js/index.js:69:5)
    at async getProduct (file:///Users/fabio/Dev/amazon/index.js:4:20)

Node.js v18.16.1
➜  amazon node index
/Users/fabio/Dev/amazon/node_modules/puppeteer-core/lib/cjs/puppeteer/util/assert.js:28
        throw new Error(message);
```

**Comment by Summaw** [comment]
Hey can you give me some more context behind what exactly your trying to get from the listing?
As you can see in my photo below that selector does not exist on the page.

![image](https://github.com/dimitryzub/ecommerce-scraper-js/assets/98126132/2a2826df-3a59-441b-8a71-e59625ed81ff)
